# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 18:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('summoners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=128)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('doublekills', models.IntegerField()),
                ('triplekills', models.IntegerField()),
                ('quadrakills', models.IntegerField()),
                ('pentakills', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.BigIntegerField()),
                ('duration', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.IntegerField()),
                ('role', models.CharField(max_length=128)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Match')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summoners.Summoner')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=128)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('doublekills', models.IntegerField()),
                ('triplekills', models.IntegerField()),
                ('quadrakills', models.IntegerField()),
                ('pentakills', models.IntegerField()),
            ],
        ),
    ]
