# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championstats',
            options={'verbose_name_plural': 'Champion Stats'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='matchstats',
            options={'verbose_name_plural': 'Match Stats'},
        ),
        migrations.AlterModelOptions(
            name='seasonstats',
            options={'verbose_name_plural': 'Season Stats'},
        ),
        migrations.AddField(
            model_name='match',
            name='riot_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
