# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0002_auto_20160602_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='lane',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='assists',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='deaths',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='kills',
            field=models.BigIntegerField(),
        ),
    ]
