# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20160602_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstats',
            name='assists',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='deaths',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='kills',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
