# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20160602_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='creation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='duration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
