# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0005_auto_20160602_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='champ_level',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='double_kills',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='first_blood_assist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='first_blood_kill',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='first_inhibitor_assist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='first_inhibitor_kill',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='first_tower_assist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='first_tower_kill',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='gold_earned',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='gold_spent',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='inhibitor_kills',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='item0',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='item1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='item2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='item3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='item4',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='item5',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='item6',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='killing_sprees',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='largest_critical_strike',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='largest_killing_spree',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='largest_multi_kill',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='magic_damage_dealt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='magic_damage_dealt_to_champions',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='magic_damage_taken',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='minions_killed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='neutral_minions_killed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='neutral_minions_killed_enemy_jungle',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='neutral_minions_killed_team_jungle',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='penta_kills',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='physical_damage_dealt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='physical_damage_dealt_to_champions',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='physical_damage_taken',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='quadra_kills',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='sight_wards_bought_in_game',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='total_damage_dealt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='total_damage_dealt_to_champions',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='total_damage_taken',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='total_heal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='total_time_crowd_control_dealt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='total_units_healed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='tower_kills',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='triple_kills',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='true_damage_dealt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='true_damage_dealt_to_champions',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='true_damage_taken',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='unreal_kills',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='vision_wards_bought_in_game',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='wards_killed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='wards_placed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='winner',
            field=models.NullBooleanField(),
        ),
    ]
