# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20160604_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='region',
            field=models.CharField(default='na', max_length=128),
            preserve_default=False,
        ),
    ]
