# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_match_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='cs_at_ten',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='cs_diff_at_ten',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='cs_per_min',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='dmg_per_min',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='gold_per_min',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='kda',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='kill_participation',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
