# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0009_auto_20160607_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='riot_id',
            new_name='match_id',
        ),
    ]
