# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_auto_20160607_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='champion',
            field=models.IntegerField(default=0),
        ),
    ]
