# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0011_auto_20160608_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchstats',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchstats',
            name='summoner',
        ),
        migrations.AddField(
            model_name='matchstats',
            name='match_duration',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchstats',
            name='match_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='region',
            field=models.CharField(default='na', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchstats',
            name='summoner_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='summoner_name',
            field=models.CharField(default='x', max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
