# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_auto_20160613_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='match_creation',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
