# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0013_matchstats_match_creation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChampionStats',
            new_name='SeasonStatsChampion',
        ),
        migrations.AlterModelOptions(
            name='seasonstatschampion',
            options={'verbose_name_plural': 'Season Stats Champion'},
        ),
        migrations.AddField(
            model_name='matchstats',
            name='summoner_key',
            field=models.CharField(default='yo', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='lane',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='region',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='role',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='summoner_name',
            field=models.CharField(max_length=32),
        ),
    ]
