# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0014_auto_20160618_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchstats',
            name='summoner_id',
        ),
    ]
