# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0015_remove_matchstats_summoner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='summoner_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
