# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0016_matchstats_summoner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='keystone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='spell1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='spell2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='lane',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='match_creation',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='match_duration',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='region',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='role',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='summoner_key',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='matchstats',
            name='summoner_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
