# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_auto_20160623_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='team_assists',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='team_deaths',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchstats',
            name='team_kills',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
