# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stats', '0020_auto_20160804_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonstats',
            name='doublekills',
        ),
        migrations.RemoveField(
            model_name='seasonstats',
            name='pentakills',
        ),
        migrations.RemoveField(
            model_name='seasonstats',
            name='quadrakills',
        ),
        migrations.RemoveField(
            model_name='seasonstats',
            name='triplekills',
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='damage_dealt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='damage_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='double_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='games',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='gold_earned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='magic_damage_dealt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='max_deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='max_killing_spree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='max_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='minion_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='neutral_minion_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='penta_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='physical_damage_dealt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='quadra_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='triple_kills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonstats',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonstats',
            name='champion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seasonstats',
            name='deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonstats',
            name='kills',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
