# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=4)),
                ('key', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('summoner_id', models.BigIntegerField()),
                ('tier', models.CharField(max_length=16)),
                ('division', models.CharField(max_length=4)),
                ('lp', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('series', models.CharField(blank=True, default='', max_length=8)),
                ('profile_icon', models.IntegerField()),
                ('friends', models.CharField(blank=True, default='', max_length=1024)),
                ('accessed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Summoner',
                'verbose_name_plural': 'Summoners',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='summoner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summoners.User'),
        ),
        migrations.AlterUniqueTogether(
            name='summoner',
            unique_together=set([('region', 'summoner_id')]),
        ),
    ]
