# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='summoner',
            unique_together=set([('region', 'summoner_id')]),
        ),
    ]
