# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='last_accessed',
        ),
        migrations.AlterField(
            model_name='summoner',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
