# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0003_auto_20160527_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='region',
            field=models.CharField(default='z', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
