# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0007_auto_20160528_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='friends',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
