# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summoners', '0008_summoner_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='riot_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
