# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0009_summoner_riot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
    ]
