# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0010_summoner_total_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='profile_icon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='riot_id',
            field=models.IntegerField(default=0),
        ),
    ]
