# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('summoners', '0012_auto_20160604_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='total_games',
        ),
    ]
