# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('summoners', '0013_remove_summoner_total_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner',
            old_name='riot_id',
            new_name='summoner_id',
        ),
    ]
