# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0014_auto_20160607_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='key',
            field=models.CharField(default='X', max_length=128),
            preserve_default=False,
        ),
    ]
