# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0015_summoner_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='friends',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
