# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0016_auto_20160609_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='friends',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='key',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='region',
            field=models.CharField(max_length=4),
        ),
    ]
