# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0017_auto_20160618_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='placeholder@email.com', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='xxx', max_length=256),
            preserve_default=False,
        ),
    ]
