# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summoners', '0018_auto_20160630_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='division',
            field=models.CharField(default='I', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoner',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summoner',
            name='series_progress',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='summoner',
            name='tier',
            field=models.CharField(default='SILVER', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoner',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
