# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('summoners', '0019_auto_20160804_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner',
            old_name='series_progress',
            new_name='series',
        ),
    ]
