# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('summoners', '0021_auto_20160804_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='lp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
