# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summoners', '0022_summoner_lp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summoners.User'),
        ),
    ]
